import Head from "next/head";
import { ChooseWemos } from "../components/ChooseWemos";
import { Header } from "../components/Header";
import styles from "../styles/Home.module.css";
import { initFirebase } from "../components/firebase";
import styled from "styled-components";
const Container = styled.div``;
export default function Home() {
  initFirebase();
  const numOfWemos = 20;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header></Header>
        <main>
          <ChooseWemos numOfWemos={numOfWemos}></ChooseWemos>
        </main>
      </Container>
    </div>
  );
}
